
# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT tutorial.wsgi

beta_settings:
    cloud_sql_instances: breadboard-215001:us-east1:breadboard-db

runtime_config:
  python_version: 3
# [END runtime]
