
# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT breadboard.wsgi

beta_settings:
    cloud_sql_instances: breadboard-215702:us-east1:breadboard-instance

runtime_config:
  python_version: 3
# [END runtime]
