# Generated by Django 2.1 on 2018-09-04 02:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sdk_id', models.CharField(max_length=100, verbose_name='a camera identifier for the computer sdk')),
                ('created', models.DateTimeField(verbose_name='datetime camera was created')),
                ('magnification', models.FloatField(default=1)),
            ],
            options={
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='time created')),
                ('notes', models.TextField(verbose_name='image notes')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quickstart.Camera')),
            ],
            options={
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.DateTimeField(verbose_name='datetime for expt run')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Variables and parameters')),
            ],
            options={
                'ordering': ['-runtime'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quickstart.Run'),
        ),
    ]
