# Generated by Django 2.1.1 on 2018-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(default='Dataset 1', max_length=200, verbose_name='Dataset name'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(default='bec1', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project1', max_length=200, verbose_name='project name'),
        ),
    ]
