# Generated by Django 2.1 on 2018-09-06 20:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import quickstart.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dataset name')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='datetime created')),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='Dataset notes')),
                ('flag', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dataset flags')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=quickstart.models.default_params, null=True, verbose_name='tags for the dataset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date lab was registered')),
                ('info', models.TextField(blank=True, null=True, verbose_name='detailed info about the lab')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='filepath to the lab photo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='project name')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='datetime created')),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='project notes')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='quickstart.Lab')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='axis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='axis image was taken from'),
        ),
        migrations.AddField(
            model_name='camera',
            name='double_imaging',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='pixel_size',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='atom',
            field=models.CharField(choices=[('Li', 'Lithium'), ('Na', 'Sodium'), ('K', 'Potassium')], default='Li', max_length=2, verbose_name='atom used in the imaging: eg Li, Na, K, etc '),
        ),
        migrations.AddField(
            model_name='image',
            name='atomsperpixel',
            field=models.TextField(blank=True, null=True, verbose_name='filepath location for the atoms per pixel on / in the MIT server'),
        ),
        migrations.AddField(
            model_name='image',
            name='cropi',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=quickstart.models.default_params, null=True, verbose_name='cropi for the image'),
        ),
        migrations.AddField(
            model_name='image',
            name='filepath',
            field=models.TextField(blank=True, null=True, verbose_name='filepath location for raw data on / in the MIT server'),
        ),
        migrations.AddField(
            model_name='image',
            name='odpath',
            field=models.TextField(blank=True, null=True, verbose_name='filepath location for the od fits file on / in the MIT server'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=quickstart.models.default_params, null=True, verbose_name='tags for the image'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='filepath for an image thumbnail'),
        ),
        migrations.AddField(
            model_name='image',
            name='total_atoms',
            field=models.FloatField(blank=True, null=True, verbose_name='number of atoms in the image. Can be either from fitting or from pixel summing'),
        ),
        migrations.AddField(
            model_name='run',
            name='bad_shot',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Was this run a bad shot?'),
        ),
        migrations.AddField(
            model_name='run',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='datetime object created. Could be different by a few sec from runtime'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='datetime camera was created'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='magnification',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='sdk_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='a camera identifier for the computer sdk'),
        ),
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='quickstart.Camera'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='time created'),
        ),
        migrations.AlterField(
            model_name='image',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='image notes'),
        ),
        migrations.AlterField(
            model_name='image',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='quickstart.Run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=quickstart.models.default_params, null=True, verbose_name='Variables and parameters'),
        ),
        migrations.AlterField(
            model_name='run',
            name='runtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='datetime for expt run'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='quickstart.Lab'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='quickstart.Project'),
        ),
        migrations.AddField(
            model_name='camera',
            name='calibration_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Dataset'),
        ),
        migrations.AddField(
            model_name='run',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='quickstart.Dataset'),
        ),
        migrations.AddField(
            model_name='run',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='quickstart.Lab'),
        ),
    ]
