# Generated by Django 2.1.1 on 2018-09-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20180906_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='double_imaging',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='bad_shot',
            field=models.BooleanField(blank=True, default=False, verbose_name='Was this run a bad shot?'),
        ),
    ]
