# Generated by Django 2.1.1 on 2018-09-11 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180907_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='workday',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='date of lab work. (often overflows through midnight)'),
        ),
    ]
