# Generated by Django 2.1.1 on 2018-09-11 15:38

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_camera_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=api.models.default_params, null=True, verbose_name='additional settings, such as Isat, fudge, subsample, etc'),
        ),
        migrations.AddField(
            model_name='run',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Run notes'),
        ),
    ]
