# Generated by Django 2.1.1 on 2019-01-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180911_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['-created', 'name'], 'verbose_name': 'camera', 'verbose_name_plural': 'cameras'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name'], 'verbose_name': 'dataset', 'verbose_name_plural': 'datasets'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created', 'name'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ['name'], 'verbose_name': 'lab', 'verbose_name_plural': 'labs'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'project', 'verbose_name_plural': 'project'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-runtime'], 'verbose_name': 'run', 'verbose_name_plural': 'runs'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'userprofile', 'verbose_name_plural': 'userprofiles'},
        ),
        migrations.AddField(
            model_name='image',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.Lab'),
        ),
    ]
