# Generated by Django 2.1.1 on 2019-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190111_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='calibration_dataset',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='image',
            name='camera',
        ),
        migrations.AddField(
            model_name='image',
            name='pixel_size',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
