# Generated by Django 2.1.1 on 2019-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190312_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='atom',
            field=models.CharField(choices=[('Li', 'Lithium'), ('Na', 'Sodium'), ('K', 'Potassium')], default='Li', max_length=2, null=True, verbose_name='atom used in the imaging: eg Li, Na, K, etc '),
        ),
    ]
