# Generated by Django 2.1.1 on 2019-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190312_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='bad_shot',
        ),
        migrations.AddField(
            model_name='image',
            name='bad_shot',
            field=models.BooleanField(blank=True, default=False, verbose_name='Was this image a bad shot?'),
        ),
    ]
