# Generated by Django 2.1.1 on 2019-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190313_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bad_shot',
            field=models.NullBooleanField(default=False, verbose_name='Was this image a bad shot?'),
        ),
    ]
