# Generated by Django 2.2.9 on 2020-08-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190313_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='workday',
        ),
    ]
